language: node_js
node_js:
  - node
before_install:
  - npm install -g now
before_deploy: npm run build
deploy:
  - provider: script
    script: now --public --token $NOW_TOKEN && now --prod --token $NOW_TOKEN
    skip_cleanup: true
    on:
      branch: master
env:
  global:
    - TEST_NPM_USER=aggre
    - secure: GbbOvHLDBKiB9EFelqjIMw4pastAA20V3nYrVuMfaULtZGmZEDGfoRZV/Uon1UmbF84IzunDvi46Iuz4LVLGSpggTG+tukEOvX6Y0ELrGZ6U88Y6nZMEAwEXtQWqp06/z1nIpFyb1JcegqM+kSWsYEX2RoFg67NoFPpKryw8XO2bXCzLddg0mjQcIQ8X7hwTYrUFcyi/mSzj7isSYvDsx4H0oPQI6keSKZX3+Q9VhY4YY8YnV2bOmbqQPlXfYHRBP7r/h4akgvVmYpeAAyIYc6f6rmW5PsZL+PU6/yX6GLZQbWyXl7odBCmkK9oMW8HZfoE72EPiyskA4yFfGd1TfPw14K2QdY04krOK4mB0WOPhX3rKoJvE/NBKZCgh1DPLly/MoSm4MdxiRHgI2ctll4Y/b8M7ut0DJE7XYLyZcagA3T/nLHAVb9R7JNar76SfcqiEahHX2lgjfTQGLjnRwwOU56n+faErPEsXmFxoeTLfgaeTjCa1sT/ehLtNI+tg42SNn3oAbdodFvajZEizsyrUTQJN1gXV/jOZ3aMRaUz7tnGnbFTTvrREjFXVk4mH2rdgPCe6JO5hpFkHcsAn7/M52CTfk7IxurwNXlmllJZOvsr1g+Dlek+qC/8eGLERLscTFZ9s5+wwEc+GvPDpWoWJ58oBq5CYeB4Bldb8RVs=
    - secure: HiTfv4KBDoqJ0Rq7pXIyGVmN5MAxs/AhiISjHO2nVg82XntB5NGIihM7nCATWnCLeB9JPXrVCk9YQzdiHNy2P6hG2tfFfSrxBDkIyXnA065cRAE22P3fQ/xY0VorDPyslaXuHYFabl+xfSQtkNtSAcHTbGrH3Y5tpuUUoZsqKV98A9laqFt94bX0uwfYeO608Q6CAOMEXewmty7Nf+ASCDkE40ZvnUplEfHkMSHrEmwCpRY7FONw6KB96xsMamJxfy1qEUXvGVpVCfn5rfHRG9KqvvaQMic0orTy8DQHFzP+3iBeL5q94YWrdTFfH2SPpAbDBDObzC8g0KW0zN45CQZo8iRnFdhRnr6sdvBrC+qHnhYY230e8rsPfV+IvkrJtXW7vm7fMiG5XAd8nblSulTYN5PkK4OxJO6fgZjBZo9suVbmxAr9PdNTBVoem8bRvipvQT+0kKF5UB5xbQ13SJJpWPrINccpfgq5W3s5MdIpwaGShfI/ydXGAnkRw9n8oFfTqpzRyjeul+P0/c4MCBARbpq2hA1vVOVUH9o2doyI+7uS3U7D+kBPYxb2Scsq/0iBbDEQ0R7bV6guoRjv3dYQkAT2Hqj1xOuYYhzQgyr/rfl/NVGouJgQ5nHYAjWXml7rear838FulaAbNqIWoU+I/jIN/0MzpxCDgLdKNnA=
