language: node_js
node_js:
- node
before_install:
- npm install -g now
before_deploy: npm run build
deploy:
- provider: script
  script: now --public --token $NOW_TOKEN && now alias --token $NOW_TOKEN
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - TEST_NPM_USER=aggre
  - secure: LPkCWxNXeuZd5tvKhmmqzWfF3SYBQdpRouQV5eoNw0PxcoMjAmVwetIB4Y45iCpBO+CQ6yAqlkUCO6nwJdGCEvy4nvMB1JwDf56jSR5XXWVe9xnttZGA1201DpEJdg6nyCJRdVGQlNxIwglVj5b0P4TOAfXbunZEzneZg1D7P3D5GAtt663ACwR7KGHx5nAuqoOguoCj3c8mqH2NldvcOGxbq8bxIb3Sy1skR6xUPJat941D9HRW6Hqoh7i5dhh+zAr4qQ9EJOhVsI5Y69MWRORnG7cW7VcoJFuAOlbewNl4+e0VwkCEotqmWoLNQg5J5GRsj6NCKjLRhIzHSLXEq6iFbP+TZeWQN9NlEIXy41sB3s7hpNXjuNoJqzO46WQYt3mR/4WYYAs/xdfNwyHVZ1XM/dCMVWgzPkNOb1IDuwsTkHZWZL0Sr6T8VlxryMEEyySH0uQ6w2gWOrl8Kb2W2Ed2F/IcUDIOFqGL8ZdAFqPne1HQw1H3n2cu5iSb6mtuQY2WWirqosZ8G3jF6yxDUsz41IToD6fVM8Pi0I54uk80UQGvY1mBsrEligt9+IRnE/uCCF856bwsXtAoEId21TGkEwfcHNmXss8p4cFqMQTXzYFD6Mpx8Aog30ZFkDNr8QDuTznyn/Q0+zWcjEGm4VhyccNTCTt2VCadyoYYbSM=
  - secure: udgf9OOgg3hShbMa0wxKguzuo4v5tQG2yhjebTzKNneb47MUqkveYz86DkiW7k3zKJji7CGBXNvFWYLIIvjZH7l4WbggfLoRPN3vIu8rsUCMkWX2BbbIj6qzGgCLZU8rAezoJRXnolZqFHORi0Wh6cHzAK/Xko0xmT7NesehI5tficy2pxkXm1mDTK8ofy4sFN62nlxGz0upm5STjiHvWfdGBZ8PSzvxRDaDTQTXGQkJqBylkLlUYAO5Qciy4/1R34E7CAiPY+8WyAkXz4I9yTrjdjzeRcDeK66LlHFk7JAzWdDTZ22W7mY9hrzUMRbISm/I2EstHCwYFE41dAhVhINKiZ28KJXQEl+7cx3LlRux5FpoIqB37xCmVGW5QwFw7E97naHJ46jk0kofvlldpm6dMVVNe4eDARVN5nnhQ1gOwrk8F+o9TSG3PV0xk9sa2yZDep3tIDK9n/V5ZhKEYVjeJusSXvNQ5ctP/+Gayr9C++ooylE/QGyyQa2KvV1hldkPTtIugzRZpWgx8s2WpqiCSiEeyrK896S4gPmo+N+zCo1hKV+nGVY14YDKGVOIMQSosu/16d5YFHHQO5GbEl6EtbY9Kk8HNfrnfq+Bptz0MN8lQjBMXid2BqcA0PoPe734SrtyfvYBA+DAaR9vjcz0yWQaoCJHgYJbCsWaXn4=
